pipeline {
    
	agent any
	
    environment {
        cluster = "vproprod"
        service = "vproappprodsvc"
    }
	
    stages { 
        stage('Deploy To ECS Prod'){
          steps{
            withAWS(credentials: 'awscreds', region: 'ap-south-1'){
              sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
            }
          }
        }
    }

}
